### ISSUE TITLE
S3 service for local development

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/GoGovSG#117]
**Is your feature request related to a problem? Please describe.**
Development today requires the use of an actual S3 bucket to be set up on AWS.

**Describe the solution you'd like**
Add an S3 service such as _localstack_ to the local development environment.

**Describe alternatives you've considered**
An alternative service to consider is _Minio_.

**Comment by LoneRifle** [comment]
see opengovsg/postmangovsg#284
