### ISSUE TITLE
Show appropriate error message when user try to shorten a go.gov.sg link

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#1175]
Currently when a user tries to shorten a go.gov.sg link, it will show a "Server error" message. This error message is not easily understandable and can lead to user confusing that there might be some other problems with their account.

A more accurate error message should be "You cannot shorten a go.gov.sg link"

<img width="985" alt="Screenshot 2021-02-09 at 5 45 54 PM" src="https://user-images.githubusercontent.com/23736580/107345558-a9ec3880-6afe-11eb-9e93-bd084d6d7ddc.png">

**Comment by liangyuanruo** [comment]
Strange that it's not showing the other error along the lines of "you cannot create a link to other link shorteners". We should look into this.
