### ISSUE TITLE
Missing description on homepage

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#1354]
See screenshow below:
<img width="987" alt="Screenshot 2021-03-25 at 2 26 52 PM" src="https://user-images.githubusercontent.com/23736580/112428444-26b53800-8d76-11eb-9c4b-a2bef186a4b7.png">

**Comment by IDXNTCXNAJM** [comment]
> See screenshow below: <img alt="Screenshot 2021-03-25 at 2 26 52 PM" width="987" src="https://user-images.githubusercontent.com/23736580/112428444-26b53800-8d76-11eb-9c4b-a2bef186a4b7.png">

🎁
