### ISSUE TITLE
API for Programatic Access

### ISSUE THREAD

**Issue by qinjie** [opengovsg/GoGovSG#1638]
Does go.gov.sg provides programatic access for developers? 

We would like to use the API to generate shortened URL through API calls. We would also like to know frequency of activation (and maybe timing of activations) fo the shortened url for analytics purpose. 

Does current https://go.gov.sg already have such feature?

**Comment by liangyuanruo** [comment]
Hi @qinjie, due to resourcing constraints amidst the pandemic, supporting programmatic access (and the operational load that would introduce) is a specific non-goal of the team. We do not have plans to introduce any new features for the foreseeable period. Hope you can understand.
