### ISSUE TITLE
The vaccination status in the trace together app suddenly vanished 

### ISSUE THREAD

**Issue by MekalaiRajkumar** [opengovsg/GoGovSG#1739]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LoneRifle** [comment]
Not relevant to GoGovSG itself. Please direct issues pertaining to TraceTogether using the links [here](https://support.tracetogether.gov.sg/hc/en-sg/categories/360003172053-Contact-Us).
