### ISSUE TITLE
Fix secrets-check script

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/GoGovSG#1762]
Identical issue as this: https://github.com/opengovsg/askgovsg/issues/1134

**Comment by tan-zx** [comment]
Sorry I realized my previous PR had a typo >< Thanks @tshuli

**Comment by tshuli** [comment]
@tan-zx jiayou! 👍

**Comment by yong-jie** [comment]
closing as this has been done via #1771. Thanks for the help!
