### ISSUE TITLE
Indicate which link the user is editing on edit link drawer

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#180]
**Is your feature request related to a problem? Please describe.**
Currently when user select on a link to edit, the drawer does not indicate which link the user is editing. This may cause confusion for users especially those who has a large number of links in their account. 

**Describe the solution you'd like**
Display on the drawer the link that the user is editing
![Screenshot 2020-06-11 at 2 28 43 AM](https://user-images.githubusercontent.com/23736580/84305295-6d8dc480-ab8c-11ea-8afb-eff3a9f2ac2d.png)

**Comment by pearlyong** [comment]
proposed design:
https://www.figma.com/file/nnn9vEU4WeMKiddwEUSnAW/Go.gov.sg?node-id=5779%3A1170
