### ISSUE TITLE
Update copies for for.sg 

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#1803]
Update list of assets [here](https://docs.google.com/spreadsheets/d/1JxEluLo4yI5tXPWEYAdrejiKBGpcD97wTRJC7ysAyx4/edit#gid=0)

**Comment by henashah7** [comment]
Updated the list and separated out by pages/user flows.

- Need some clarification on terminology to use: "Healthcare Officer", "Healthcare Staff", "Healthcare worker" ?

**Comment by henashah7** [comment]
We will be using "Healthcare Professionals" terminology across the product
