### ISSUE TITLE
Link Search

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/GoGovSG#181]
# Technical Proposal

### Overview

Members of the public (MOPs) view go.gov.sg as a central hub for accessing government resources. By providing a link search feature, we will be able to better direct MOPs to access the resources that they require.

### Goals
- Admins must be able to _optionally_ provide search description and keywords for each link.
- Users must be able to search _performantly_ based on the description provided.
- Search functionality should be powered by [Postgres Full Text Search](https://www.postgresql.org/docs/9.5/textsearch-intro.html)
- Search results should be ranked by a relevance algorithm that balances
  - [Textual rank](https://www.postgresql.org/docs/9.5/textsearch-controls.html) as determined by Postgres
  - Total number of link clicks
  - Recency

### Non-Goals or Out of Scope

Due to the limited amount of text expected, we will not be considering a separate search database such as ElasticSearch.

We will not support searching by agency or user email.

### Design

- Extend the current `Url` and `UrlHistory` table to accept a new `description` and `keywords` column
- The column should be indexed by a GIN index configured to _english_. There may be a need to restrict saved text to english / ASCII
- Expose a public `/search` API for the frontend

### Test Plan

Explanations of how the tests will make sure user requirements are met
Unit tests
Integrations tests
QA

### Monitoring and Alerting Plan

To monitor alarms for expected load increase on the database (CPU, IOPS) after rollout.

#### Maintenance
Implementation should rely on GIN indexing to maintain the preprocessed _ts_vector_ instead of manually introducing database triggers.

#### Security
- Implementation should protect against SQL injection given that API is public and raw queries are expected to be used for this feature

### Future Work

- Fine-tuning search relevance algorithm
- Logging user search behavior

### References

https://www.postgresql.org/docs/9.5/textsearch-controls.html

**Comment by LoneRifle** [comment]
Given search is now in soft-launch, I will have this issue closed. Follow-up work to be tracked through other issues.
