### ISSUE TITLE
Tooltip is not accessible on mobile

### ISSUE THREAD

**Issue by halfwhole** [opengovsg/GoGovSG#1921]
**Describe the bug**
Mobile users cannot see the tooltip. It only appears when the cursor hovers over it, but this function is not available on mobile

**To Reproduce**
For example, we can go to the "Edit link" drawer, scroll down to the "Link owner" section, and attempt to use the tooltip there:

![Screenshot 2022-08-17 at 10 35 16 AM](https://user-images.githubusercontent.com/41856541/185025777-77f0da02-46c8-44d9-a76f-d727e6b81849.png)

**Expected behavior**
Mobile users should be able to view the tooltip, e.g. perhaps by clicking on it

**Environments:**
- Can replicate using Chrome on desktop in mobile mode (through devtools)
- Can replicate using Firefox or Chrome on a smartphone

**Comment by jimvae** [comment]
Tried it works on my mobile phone.  To simulate this on Desktop Chrome in mobile mode, you have to press and hold to activate the tool tip
<img width="596" alt="Screen Shot 2022-09-26 at 9 58 30 AM" src="https://user-images.githubusercontent.com/65295129/192179250-914f68ac-1d84-466c-a755-03151158fcd7.png">

**Comment by halfwhole** [comment]
thanks for the catch!
