### ISSUE TITLE
Login UI bug

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/GoGovSG#204]
**Describe the bug**
The login button is not disabled when two email addresses are supplied in the login field. The backend still rejects the request however due to `validator.js`' email validation.

**Expected behavior**
The sign-in button should be disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/5690550/84924493-2c049880-b0fb-11ea-8a39-9f4478295b58.png)

**Comment by lisatjide** [comment]
Validations also did not catch whether input is an email, anything that ends with .gov.sg will work 
![Screenshot 2020-07-03 at 5 16 24 PM](https://user-images.githubusercontent.com/23736580/86453886-0d381000-bd51-11ea-9d23-9dd4bb77f478.png)
