### ISSUE TITLE
Investigate drop off from transition page 

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#205]
**Describe the issue**
GA logs has shown that the drop off at transition page is 17.4%. This means that close to 20% of the users did not proceed after transition page is being served. 

Further investigation has to be done to further find out the root cause of this high number of drop off, specifically to find out if there is any systemic issues such as browsers, devices or platforms where links are shared. We will then be able to take corrective measures or inform users affected.

**Comment by LoneRifle** [comment]
Drop off has since reduced significantly owing to changes we have made to the transition page.
