### ISSUE TITLE
E2E tests

### ISSUE THREAD

**Issue by gweiying** [opengovsg/GoGovSG#2124]
Add the following E2E tests:

## User page
- [ ] Ellipses are shown for very long links

## URL creation
- [ ] It should prevent uploading when a [malicious file](https://www.webroot.com/blog/2018/09/05/eicar-common-false-positive-world/) is submitted
 
## URL Searching and Download (?)
- [ ] Clicking on the download button downloads all links currently shown in the links table as a `.csv` file.

## User page - Sort & Filter
- [ ] Links should be sorted by their number of clicks in descending order when enabling sort by `Most number of visits` and clicking apply

**Comment by oversparkling** [comment]
> Ellipses are shown for very long links
It seems that this might be a bit tricky to test. The truncated text (with the ellipsis) is not accessible by any HTML property given. `innerText` and `textContent` will return the full length string instead. The only way I can "test" this would be via checking the overflow property style of the text, which is quite trivial
