### ISSUE TITLE
Banner does not show lion head symbol on IE11

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/GoGovSG#256]
**Describe the bug**
Lion head symbol on banner does not show up on IE11

**To Reproduce**
1. Go to the Landing Page
2. Observe that the lion head symbol does not show up on the "A Singapore Government Agency Website" banner

**Expected behavior**
The symbol should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/5690550/86438473-3482e300-bd39-11ea-9adc-621955e05eab.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser IE11

**Comment by LoneRifle** [comment]
This can be worked around by replacing the Lion Head Symbol glyph from the sgds-icons font with an equivalent .svg. This may have the added side-benefit of removing a dependency on that font.

As a stretch goal, the lion head symbol should also be similarly replaced on the transition and 404 pages.
