### ISSUE TITLE
Inconsistent SVG QR code sizes

### ISSUE THREAD

**Issue by kylerwsm** [opengovsg/GoGovSG#26]
**Describe the bug**
QR code `.svg` size changes after `.png` version is download.

**To Reproduce**
1. Log into your go.gov.sg with your `gov.sg` email.
2. Show the QR code by creating a new short link or use an existing one.
3. Download the `.svg` version, followed by `.png` and then `.svg` version again.
4. In your download folder, you will see that the two `.svg` files have slightly different sizes.

**Expected behavior**
The above-mentioned `.svg` files downloaded should be identical.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by LoneRifle** [comment]
Fixed by #27
