### ISSUE TITLE
Add scanning of files before upload [By Jul 24]

### ISSUE THREAD

**Issue by leonardloo** [opengovsg/GoGovSG#274]
It is likely we need not over-protect file uploads, given it is only available to authenticated gov.sg users. However, to prevent escalation of access rights if a gov.sg email is compromised or ignorance if a public officer unknowingly uploads a malicious file, it is still useful to prevent bad files from uploaded.

Cloudflare WAF does not seem to scan files for vulnerabilities. Can we try using packages such as clamscan? This article provides a test file with innocuous malware: https://blog.didierstevens.com/2015/08/28/test-file-pdf-with-embedded-doc-dropping-eicar/

To implement this by Jul 24 so testers can do remediation testing.

**Comment by LoneRifle** [comment]
Possible avenue, since we can then implement file scanning on both frontend and backend:
https://developers.virustotal.com/v3.0/reference#overview

Free quotas are limited to 4/min, 1K/day.

**Comment by yong-jie** [comment]
### Known alternatives

**Cloudmersive**
Much more transparent [pricing model](https://cloudmersive.com/pricing), with the primary concern being the 4MB filesize limit on the free tier.

Rate limiting at 1 API call per second, 1000 calls per month. In comparison, VirusTotal is 4 calls per minute, 1000 calls per day.
