### ISSUE TITLE
Implement HTTP Security Headers

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/GoGovSG#291]
**Is your feature request related to a problem? Please describe.**
Beef up the security of the web application, to protect against possible attacks e.g. XSS and so on.

**Describe the solution you'd like**
Implement a loader that configures the Express application to inject the following security headers with HelmetJS

CSP headers
- [ ] Content Security Policy
- [ ] Content Security Policy Report Only (can set this via an optional env var to Sentry.io)

Others
- [x] Strict Transport Security (HSTS)
- [ ] Upgrade Insecure Requests
- [x] X-Content-Type-Options
- [x] X-Frame-Options
- [x] X-XSS-Protection

**Comment by LoneRifle** [comment]
Helmet is already in use with defaults:
https://github.com/opengovsg/GoGovSG/blob/d92f50a63cf9cf5ee47f1e3ba914572ff45af5f0/src/server/index.ts#L64

I'm checking off what has already been implemented
