### ISSUE TITLE
Words in text boxes got cut off on iphone7

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#3]
**Describe the bug**
Upon logging in on an iOS device (iPhone7), the text inside the text boxes got cut off

**To Reproduce**
1. Log into go.gov.sg
2. Click on 'Create link' button
3. When you type something into the textboxes, the words will be cut off (see below)
![image (2)](https://user-images.githubusercontent.com/23736580/78772038-b5913f00-79c3-11ea-9a99-720ecc00c983.png)

**Expected behavior**

The words in the textboxes should not be cut off
![Screenshot_2020-04-08-17-48-42-23](https://user-images.githubusercontent.com/23736580/78772079-c80b7880-79c3-11ea-91ff-4968c4e90424.png)

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: -
 - Browser: Chrome
 - Version: -

**Comment by reiallenramos** [comment]
Happens in iPhone 6 as well, for Chrome and Safari. Tried disabling CssBaseline, didn't do the trick.
