### ISSUE TITLE
Improve invalid domain toaster messages

### ISSUE THREAD

**Issue by kylerwsm** [opengovsg/GoGovSG#31]
**Describe the enhancement**
Currently, our domain expression is fetched from the backend when user is routed to the login page. But since we are using client side routing, there may cases where users fetch the app but not the domain expression (i.e. bad or no connectivity when clicking on the login button). When that happens, the app does not prompt the user when he/she is using an email with an invalid domain.

While our backend does our good job in picking invalid domains, the message shown in the error toaster might not be intuitive enough for the user to think that the domain they are using is invalid. Relevant screenshot below.

_Edit for more context: Some relevant files to look at may be the [verify email](https://github.com/opengovsg/GoGovSG/blob/4077ff7f85a8dbb6ac770a72b502280d2458d237/src/server/api/login.ts#L95-L188) api endpoint (which returns the verification toaster text) and the [environment variables](https://github.com/opengovsg/GoGovSG/blob/master/README.md#setting-up-the-infrastructure) (to find the valid email domain used) in our app._

**Screenshot**
![image](https://user-images.githubusercontent.com/28863045/79193567-7482aa00-7e5d-11ea-8c75-cffe6ed970e5.png)

**Comment by fterh** [comment]
Hi, I'm not entirely clear what this issue is about.

> While our backend does our good job in picking invalid domains, the message shown in the error toaster might not be intuitive enough for the user to think that the domain they are using is invalid.

There seems to be client-side validation in https://github.com/opengovsg/GoGovSG/blob/master/src/client/components/LoginPage.jsx#L152-L154 that does feedback that "this doesn't look like a valid gov.sg email", and since this is client-side validation it will not fail even in poor network conditions.

Is this issue about updating the toaster message only?

**Comment by kylerwsm** [comment]
Yes, your edit is correct. While there is client-side validation, the domain to validate with is fetched during runtime (which relies on network connection).

**Comment by fterh** [comment]
So this issue is simply to change the toaster message to be clearer on what went wrong?

**Comment by kylerwsm** [comment]
Yes that is correct. Also, reminder to make use of environment variables or the existing translation file if you intend to show messages containing the required email domain.

**Comment by fterh** [comment]
> Also, reminder to make use of environment variables or the existing translation file if you intend to show messages containing the required email domain.

Gotcha. 

I also want to bring up something that popped into my mind. `gov.sg` is [hardcoded](https://github.com/opengovsg/GoGovSG/blob/master/src/client/locale/en/translation.js#L3) in the client bundle. I searched the repo, and the only usage of that is in LoginPage.jsx. In this case, would it make sense to hardcode the validator expression into the client bundle as well? This fixes the problem of not being able to retrieve the expression under bad network conditions.

**Comment by kylerwsm** [comment]
> > Also, reminder to make use of environment variables or the existing translation file if you intend to show messages containing the required email domain.
> 
> 
> 
> Gotcha. 
> 
> 
> 
> I also want to bring up something that popped into my mind. `gov.sg` is [hardcoded](https://github.com/opengovsg/GoGovSG/blob/master/src/client/locale/en/translation.js#L3) in the client bundle. I searched the repo, and the only usage of that is in LoginPage.jsx. In this case, would it make sense to hardcode the validator expression into the client bundle as well? This fixes the problem of not being able to retrieve the expression under bad network conditions.

While your method will work, it also assumes that the hardcoded domain used in the frontend the env var domain used in the backend will always be consistent. I believe as much as possible we should not make assumptions like that.

Maybe you can explore using the backend to also send the required domain as part of its response when the user tries to log in with an invalid domain.

**Comment by liangyuanruo** [comment]
I think the approach discussed is incomplete. Under poor network conditions, the user may not be able to do any of these:

1. Load the site
2. Fetch the glob expression
3. Send login email to server to obtain OTP
4. Submit the OTP

One cannot rely on the server to send additional messages when the problem is poor network connectivity in the first place. Instead, displaying a message indicating poor network connectivity is good enough.

As for #50, introducing a mandatory environment variable simply to display a portion of the error message is low value and also an overly onerous requirement for system deployment. Simply improving the message to e.g. "Email domain is not whitelisted" will suffice.

**Comment by LoneRifle** [comment]
> I think the approach discussed is incomplete. Under poor network conditions, the user may not be able to do any of these:
>
> _[abridged for brevity]_
>
> One cannot rely on the server to send additional messages when the problem is poor network connectivity in the first place. Instead, displaying a message indicating poor network connectivity is good enough.

While correct, perhaps this should be hived off into a separate issue, so that the PR can focus on delivering an appropriate message on addressing this particular issue

**Comment by leonardloo** [comment]
As discussed, this PR's focus is to deliver an appropriate message. Addressing UI issues under poor network conditions is in a new issue #51

**Comment by liangyuanruo** [comment]
OK. It seems to me the simplest approach is to just update the error message.
