### ISSUE TITLE
Search from the browser address bar by supporting the OpenSearch description format

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/GoGovSG#389]
**Is your feature request related to a problem? Please describe.**
Allow browsers to discover search functionality on the site and support direct search from the address bar, just like [gov.uk](gov.uk).

**Describe the solution you'd like**
Implement the [OpenSearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) description format.

**Describe alternatives you've considered**
N/A

**Additional context**
This should be completed after search on the home page is released to the public.

**Comment by LoneRifle** [comment]
Closing in the wake of reprioritisation
