### ISSUE TITLE
Transition page countdown to be reduced to 6s

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#398]
**Is your feature request related to a problem? Please describe.**
Current transition page have a countdown timer of 8s. Upon investigation, the drop off on transition page remains at about 14.3%. By decreasing the transition countdown period, we want to bring down the drop off even further to less than 10% 

**Describe the solution you'd like**
6s transition countdown instead of 8s.

**Comment by LoneRifle** [comment]
Duplicate of #395
