### ISSUE TITLE
Security review of upload implementation

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/GoGovSG#40]
S3 bucket
- Verify upload permissions are correctly set
- [CORS headers](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) for PUT requests are limited to go.gov.sg domain

Presigned URL
- [ ] API route to generate a presigned URL requires login
- [ ] Verify that implementation uses MD5 hash for upload integrity
- [ ] Upload links expire after 5 minutes

Prerequisite #35

**Comment by lisatjide** [comment]
outdate issue

**Comment by liangyuanruo** [comment]
Feature was not implemented as a client-side upload because we wanted atomicity
