### ISSUE TITLE
Ellipsis for extra long links

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#411]
**Describe the bug**
When user create a extra long link, the user table will overflow and this pushes the other columns out of sight. 

**To Reproduce**
1. Log onto go.gov.sg 
2. Create a shortlink with more than 150 characters

**Expected behavior**
Ellipsis should be used on the link when the width of the screen/window can no longer fit the width of the row while ensuring other columns remains visible.

**Screenshots**
![Screenshot 2020-08-14 at 12 30 41 PM](https://user-images.githubusercontent.com/23736580/90214059-fa255f00-de29-11ea-9f96-93ef3ec492f2.png)

**Comment by LoneRifle** [comment]
This should apply both to long and short link entries

Stretch goal - A tooltip should appear on hovering over a link truncated by ellipsis

**Comment by jials** [comment]
Hi I would like to take up this issue if it is OK!

**Comment by liangyuanruo** [comment]
> Hi I would like to take up this issue if it is OK!
> 
Sounds great... Thanks for your help!
