### ISSUE TITLE
Link owner search on userpage

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#420]
**Is your feature request related to a problem? Please describe.**
Users coming to the go.gov.sg team to look for the owners to links that have been created but deactivated and take over the ownership. Sometimes the officers within the same agencies are not aware of who owns a particularly link which was previously created. 

**Describe the solution you'd like**
A feature to simply allow link owners to search for link owner of an identified shortlink.
Link owners can then reach out to other link owners independently without having to go through the Gogovsg team. 

This can be done through a simple query through the `URL` table to identify user ID of the link owner, this will then be mapped to the corresponding ID in the `User` table

<img width="944" alt="Screenshot 2020-08-14 at 4 50 17 PM" src="https://user-images.githubusercontent.com/23736580/90231786-3ec2f180-de4e-11ea-9980-7e7fccabfb71.png">

**Comment by LoneRifle** [comment]
Proposal - if the user is logged in, disclose the link owner in GoSearch

**Comment by lisatjide** [comment]
GoDirectory is a version of the current GoSearch feature to allow public officers to search for the ownership of links.  

**Describe the solution you'd like**
List of proposed changes: 
1. Front End - pending design 
- Add icon to show if a link is active or inactive
- Replacing “for enquiries:” to user icon
- Change link name to match the one in admin dashboard
- Include email of link owner when fetching results
- Include all active/inactive links
- Remove description

2. Access
GoDirectory will only be available to users who've logged in. 

Other considerations
- When user create a taken link, show in the error message (lead them to directory)
- Acquisition channel

**Comment by LoneRifle** [comment]
May be resolved by #640

**Comment by NatMaeTan** [comment]
Screens for Directory: https://www.figma.com/file/nnn9vEU4WeMKiddwEUSnAW/Design-Master?node-id=8561%3A29971

**Comment by lisatjide** [comment]
Created a new issue for Go Directory #672 - closing this
