### ISSUE TITLE
Avoid confusion between I, 1 and I in rendered URL

### ISSUE THREAD

**Issue by zej20** [opengovsg/GoGovSG#433]
I was recently sent a go.gov.sg url. The last character seemed to be either a 1 or a I. (I tried both but both failed. I guess there's another problem in there somewhere but let's deal with this first.) I think it is quite annoying for users to have to try both characters.

Could the code just avoid using "1" and "I" in the generated URL? 

Granted, the poster I received had a QR code I could scan but it just adds additional complexity for the user in some cases. In my case, I was accessing the file from a computer and could not scan the QR code. Making the generated URL clickable in the QR code could be workable too I guess.

![gov url](https://user-images.githubusercontent.com/69882468/90585406-5eb83380-e207-11ea-8d6f-683472344880.png)

**Comment by LoneRifle** [comment]
Hey @zej20 , and thanks for pointing out the usability problem! Given that you imply that you were reading the link and typing it in, would you think that using a different font to render the text would better aid users in accurately identifying the characters?

Fwiw, I believe the character is the letter L in lowercase.

**Comment by zej20** [comment]
Thank you, @LoneRifle ! It is indeed L in lowercase. I'd forgotten about that. Haha. 

I am not sure about the complexity in the coding but I'd thought that avoiding the characters "1" (numeric one), "I" (uppercase I) and "l" (lowercase L) in randomly generated urls could be a straightforward solution. Those characters could still be kept as an option for custom urls requested by officers when they are contextually relevant as a word (eg: https://go.gov.sg/besafe-learn). Would this be possible? The alternative solution may not be needed if we side-step the problem I think. 

A different font could be workable if there is font that can clearly differentiate between "1", "I" and "l" I guess.

**Comment by yong-jie** [comment]
It looks like the code responsible for random generation is found over here. If we were to make this change it could be as straightforward as replacing lower-case 'l' to upper-case 'L' in `ALPHABET` etc.

https://github.com/opengovsg/GoGovSG/blob/4e172094bf7b7e87814562762cc5019a8b5ccb44/src/client/util/url.ts#L3-L14

**Comment by LoneRifle** [comment]
I'm hesitant about that since it would violate the Principle of Least Surprise in some angles. I would lean towards using a font that helps users distinguish between the three characters

**Comment by liangyuanruo** [comment]
> it could be as straightforward as replacing lower-case 'l' to upper-case 'L' in ALPHABET etc.

No, that would not be backwards compatible with existing functionality, as we automatically lowercase all short links that visit the redirect URL.

**Comment by zej20** [comment]
I agree that replacing lowercase L to uppercase L might potentially surprise the user if all the other characters used are lowercase. What if it is taken out entirely? This is what I am suggesting: 

`const ALPHABET = '023456789abcdefghijkmnopqrstuvwxyz' `

I think this solution would not catch the user off guard since the user will not even encounter the characters that are hard to differentiate. But looking at the code, the associated issue would be the increase in the chance of a collision. I'm not sure how significant that might be.

Actually, having seen that code and realising that all the alphabets used are of lowercase, I think the problem is less significant now. But it is still potentially a problem as new users may not know that all the alphabets are of lowercase and may thus confused.

**Comment by LoneRifle** [comment]
The Principle of Least Surprise also applies to engineers maintaining the codebase. My main concern is with implicit assumptions held by contributors as they go about making changes; the fewer the better. 

Dropping 1, l and I might catch maintainers off-guard or at least add to the mental overhead whilst actively developing GoGovSG. My inclination for now will be to figure a way to better render the text in the image generated to users

**Comment by zej20** [comment]
I see. Fair enough.

**Comment by liangyuanruo** [comment]
TODO - Investigate using a serif font to render the URL.

**Comment by zanechua** [comment]
Font Styles in GNU FreeFont:

![image](https://user-images.githubusercontent.com/4265429/97554825-4c7e2100-1a12-11eb-9d56-16ee3fb4b5b5.png)


IMO FreeMono would be a good choice.

**Comment by LoneRifle** [comment]
I'm not keen on FreeMono to be honest, and gravitate towards using FreeSerif. @NatMaeTan - care to weigh in here?

**Comment by LoneRifle** [comment]
We might want to swap ttf-truefont with [font-ibm-plex-nerd](https://pkgs.alpinelinux.org/package/edge/community/x86/font-ibm-plex-nerd). This should give us the IBM Plex font whose sans-serif is readable, and lines up with what we are already using in Go.
