### ISSUE TITLE
Login snackbar persists through the User page

### ISSUE THREAD

**Issue by reiallenramos** [opengovsg/GoGovSG#48]
**Describe the bug**
A race condition happens between a server request and a ReactRouter redirection.

When a logged in user refreshes the /user route, LoginPage requests from the backend for a message to be supplied to the snackbar:
```
    get('/api/login/message').then((response) => {
      if (response.ok) {
        response.text().then((text) => {
          if (text) setLoginInfoMessage(text)
        })
      }
    })
```
But once the function resolves, ReactRouter has finished re-routing to the /user route -- displaying a misleading/unnecessary message.

**To Reproduce**
1. Login with email, enter OTP
2. While in `/#/user`, refresh the page

**Expected behavior**
1. `Your OTP might take awhile to get to you.` should not be displayed during a successful login.

**Screenshots**
![snackbar-persists](https://user-images.githubusercontent.com/26242729/80081965-3afd1d80-8586-11ea-84a0-68e4de2c0640.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome

**Additional context**
Digging through the codebase tells me you're reading the environment variables server-side, even the strings intended for snackbar use. Why not just store those in `translation.js` to prevent this race condition?

**Comment by liangyuanruo** [comment]
> Digging through the codebase tells me your reading the environment variables server-side, even the strings intended for snackbar use. Why not just store those in translation.js to prevent this race condition?

As we may change the displayed message frequently, the implementation is intended to be configurable server-side without the need for making code changes.
