### ISSUE TITLE
Landing page redirects to user page after sign out on Internet Explorer

### ISSUE THREAD

**Issue by waynetee** [opengovsg/GoGovSG#5]
**Describe the bug**
User is redirected to login page when signing out, but is redirected back to the user page when he visits the landing page

Even though the user can then see the user page with the links displayed, the user cannot create or modify links while logged out

**To Reproduce**
1. Sign in on IE
2. Sign out
3. Click the logo
4. User redirected to user page

**Expected behavior**
Landing page displayed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IE 11

**Comment by yong-jie** [comment]
Upon investigation, it is highly likely that this is due to API-call responses are being cached on IE, which then causes the behaviour of 1) displaying that the user is being signed in, and 2) navigating to the user route (because the browser thinks that the user is signed in).
