### ISSUE TITLE
Link directory for admins to lookup ownership of links

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/GoGovSG#500]
**Is your feature request related to a problem? Please describe.**
Users tend to contact the team to find out ownership of links. Creating an internal directory is a simple feature that would help reduce the ops workload on the team.

**Describe the solution you'd like**
An internal directory page for link admins to find out who owns which links.

**Comment by lisatjide** [comment]
@liangyuanruo this is a duplicate of #420

**Comment by lisatjide** [comment]
closing this issue since there's a duplicate
