### ISSUE TITLE
Analytics panel

### ISSUE THREAD

**Issue by leonardloo** [opengovsg/GoGovSG#54]
**Is your feature request related to a problem? Please describe.**
It is important to agencies to monitor effectiveness of their materials. And will like to measure basic metrics such as unique users visiting, browsers visited from, channels, etc.

**Describe the solution you'd like**
1. Already hooked link information to Google Analytics
2. Extend link drawer to include charts from Google Analytics data

![image](https://user-images.githubusercontent.com/4787315/80674606-01c43080-8ae5-11ea-9803-1050545dd8e0.png)

To get started on this, we will have to share staging read access to Google Analytics with you.

**Comment by liangyuanruo** [comment]
Completed

**Comment by lisatjide** [comment]
done, implemented
