### ISSUE TITLE
Add a sitemap.xml generator

### ISSUE THREAD

**Issue by LoneRifle** [opengovsg/GoGovSG#545]
In a bid to improve our visibility on search engines, we are now looking into providing hints to crawlers so that they can better find and process our shortlinks.

A [site map](https://www.sitemaps.org/) should be provided at `/sitemap.xml`, so that crawlers will know where to go. This should be dynamically generated by querying for all `Url` table entries where `state` is active, and `isSearchable` is true.

Ensure also that the relevant sequelize query does not take too long for a table containing tens of thousands of links of which hundreds have `isSearchable` set to true.

**Comment by liangyuanruo** [comment]
Sounds like a side cache mechanism is necessary (as usual).

**Comment by xming13** [comment]
Hi 

I will kickstart the discussion for the solution for this issue:

## Proposed solution
- install [express-sitemap](https://www.npmjs.com/package/express-sitemap) to tap on its API to generate well-formatted xml.
- implement `getUrlsForSitemap` function to query for all `Url` table entries where `state` is active, and `isSearchable` is true. 
- measure performance for `getUrlsForSitemap` and sitemap generation.
- implement cache for the sitemap response. cache key: sitemap, cache value: the sitemap.xml content
- implement a dynamic endpoint for `/sitemap.xml` which will return a xml response with the sitemap content,
   e.g. `router.get('/sitemap.xml', () => {})`. The endpoint should first try to get the content from cache before falling back to dynamic generation and repopulate the cache.
- implement cache invalidation when there is update to `Url`. Depends on the performance, we can optimise it by invalidating cache only when the update will result in content change for the generated sitemap.xml
- implement a protected api endpoint that allows manual trigger of sitemap generation, could be useful for debugging and measurement purpose on production.

## Alternative solution
Cron job to generate sitemap.xml every X period and serve static sitemap.xml file.
Pros: static file is easier to scale. 
Cons: sitemap.xml may not be up-to-date, maintenance of cron job.

**Comment by LoneRifle** [comment]
> * install [express-sitemap](https://www.npmjs.com/package/express-sitemap) to tap on its API to generate well-formatted xml.
Hesitant to use this - We don't really need to generate robots.txt to go along with sitemap.xml, and the sitemap itself may not have to be too sophisticated (ie, just stating `loc` and `lastmod` may suffice). Add to that the fact that the dependency seems to be maintained by an individual, and I'm leaning towards generating it using an appropriate .ejs

> * implement cache for the sitemap response. cache key: sitemap, cache value: the sitemap.xml content
> * implement a dynamic endpoint `/sitemap.xml` which will return a xml response with the sitemap content,
>   e.g. `router.get('/sitemap.xml', () => {})`. The endpoint should first try to get the content from cache before falling back to dynamic generation and repopulate the cache.
If I can counter-propose - make use of existing Redis cache as much as possible to generate the sitemap, ie, rely on hits on the shortUrl entries for quick sitemap regeneration. The drawback of this is that a fair chunk of the link population is now held in Redis when a crawler asks for the sitemap, with implications we have to investigate further.

> * implement cache invalidation when there is new `Url` that has `isSearchable` is true, or any update to existing `Url`. Depends on the performance, we can optimise it by invalidating cache only when necessary, e.g. when the update operation will result in content change in the generated sitemap.xml
> * implement a protected api endpoint that allows manual triggering of sitemap generation, this could be useful for debugging and measurement purpose on production.
I think we can safely leave these out. Some staleness of results is tolerable given that the search engine crawlers themselves do not update the index in a manner that immediately influences search results

**Comment by xming13** [comment]
1. Good point, less dependency is good. Agree to implement it without the third party library.
2. Agree that staleness of results is tolerable. Not sure if I understand you correctly when you say leave out cache invalidation, do you mean we set the cache expiry for sitemap.xml cache to say X day and let redis take care of cache invalidation?

**Comment by LoneRifle** [comment]
>  do you mean to set the cache expiry for sitemap.xml cache to say X days and let redis take care of cache invalidation?

I meant to say that we don't have to invalidate the cache the moment a `Url` is edited, hope that helps.

**Comment by xming13** [comment]
> I meant to say that we don't have to invalidate the cache the moment a Url is edited, hope that helps.

ok, we still need to invalidate the cache when a new `Url` is created, correct?

**Comment by LoneRifle** [comment]
I don't think we even need that - a time-based invalidation should be good enough, given tolerance for staleness discussed earlier =)

**Comment by xming13** [comment]
Ok got it, thanks for the clarification!

Here is the updated solution based on the discussion:

# Proposed solution
1. implement `getUrlsForSitemap` function to query for all `Url` table entries where `state` is active, and `isSearchable` is true.
2. measure performance for `getUrlsForSitemap` and sitemap generation.
3. implement cache with time-based invalidation for the sitemap response. cache key: sitemap, cache value: the sitemap.xml content.
4. implement a dynamic endpoint /sitemap.xml which will return a xml response with the sitemap content,
e.g. router.get('/sitemap.xml', () => {}). The endpoint should first try to get the content from cache before falling back to dynamic generation and repopulate the cache. The sitemap.xml will be rendered using .ejs.

**Comment by LoneRifle** [comment]
Indicated my approval, @liangyuanruo @yong-jie wdyt?

**Comment by liangyuanruo** [comment]
A lot hinges on Point 2 given that there's >91,280 links created today. Given projected growth, the performance test would have to work for at least 300,000 links under constant load. I think it will be prohibitively expensive to generate that sitemap if we rely on the database.

What if we turn the problem on its head, and have the sitemap be generated only from cached links? Search engines still get to index the links that are relevant, and there won't be a need to serve a monstrous XML file.

**Comment by LoneRifle** [comment]
Might confuse the crawler and unfairly(?) favour links that are being actively visited, though perhaps that's the point - we don't really want the crawler to index links that may not be of interest (and hence relevance?) to users

The relevant Redis commands would be `KEYS` and `MGET key1 key2 ...`

**Comment by xming13** [comment]
May I know if the 91,280 links (or 300,000) searchable (`isSearchable` is true) and if all the cached links in redis searchable? I am assuming only searchable links need to be in sitemap and we need a way to filter them from all the cached links.

**Comment by LoneRifle** [comment]
> May I know if the 91,280 links (or 300,000) searchable (`isSearchable` is true) and if all the cached links in redis searchable? I am assuming only searchable links need to be in sitemap and we need a way to filter them from all the cached links.

It's more the fact that you will likely have to scan the table as `isSearchable` is not indexed and we're not sure we want to have it so for what is admittedly an ancillary concern.

**Comment by LoneRifle** [comment]
The more I think about this, the less I think that this is a good idea. I'm inclined to close the issue in favour of alternative approaches to advertising shortlinks to crawlers, perhaps even in a separate product.

@xming13 @yong-jie - if you agree, I'll probably close this

**Comment by LoneRifle** [comment]
Let's just not proceed with this for now, in favour of alternate approaches
