### ISSUE TITLE
Link click history 

### ISSUE THREAD

**Issue by leonardloo** [opengovsg/GoGovSG#55]
**Is your feature request related to a problem? Please describe.**
Today we only show one number for links - cumulative count. This does not help agencies who repeatedly use the same link for multiple campaigns through the year analyse popularity per campaign. Not as feasible to recirculate a new link per campaign.

**Describe the solution you'd like**
1. Start storing click timestamps
2. Display link clicks in a graph on Analytics panel
3. Given high volume of link clicks (40mil till date), scalable solution needed

See graph of clicks over time below (related issue #54 ): 
![image](https://user-images.githubusercontent.com/4787315/80674757-5b2c5f80-8ae5-11ea-9594-a3baad4b3b09.png)

**Comment by stonefruit** [comment]
Hello. Maybe storing clicks per day instead of storing individual timestamps will suffice. Since agencies probably will not use the same link on the same day, and there is probably no need for analysis by timezone.

The Google Analytics looks good, is the underlying issue the difficulty in sharing this information with the link owners?

**Comment by leonardloo** [comment]
@stonefruit You are right that clicks per day is good enough for agencies. How would you suggest implementing that though? Might be easier to increment on each click.

We are already collecting the GA data, issue #54 deals with implementing the UI to pull that data.

**Comment by leonardloo** [comment]
Updates:
1. Engineering: Implement with bucket inserts and no batch job. For e.g., link click at 12.15pm will insert into 1200 bucket and link click at 1.25pm will insert into 1300 bucket.
2. Design: Review above design to just include one graph. We will not likely implement GA anytime soon, or if at all.

**Comment by kylerwsm** [comment]
Dropping an update after having a discussion about this with @liangyuanruo.

The current direction is to implement dedicated tables for each of the three statistics that we will be showing in the drawer. These tables will be updated directly using upserts without a streaming service. Additionally, there will be no batch jobs needed for now. In this setup, we are trading write operations for real-time statistics and simplicity.
