### ISSUE TITLE
Bundle QR code with link in same image

### ISSUE THREAD

**Issue by leonardloo** [opengovsg/GoGovSG#56]
**Is your feature request related to a problem? Please describe.**
Today QR codes are in their own image. However this is a phishing risk if link is not displayed below the QR code so user has the option to check that QR code indeed directs to the link. It is also a usability issue if citizens prefer to type links than scan QR codes.

**Describe the solution you'd like**
Include short link inside image of QR code so both are shared together. Short link can be below the QR code.

**Comment by LoneRifle** [comment]
isn't the phishing risk still there, as presumably an attacker can also put the link text below the QR code in the fake image?

**Comment by liangyuanruo** [comment]
@LoneRifle yes, agree; I've pointed out to @leonardloo before that the underlying security of the link is conferred by the `gov.sg` domain and not the URL beneath the QR code display nor logo. at best, this would prompt the user scanning the QR code to watch out for the go.gov.sg domain.

**Comment by leonardloo** [comment]
@liangyuanruo @LoneRifle phishing risk is always there but this can a) remind user to check for go.gov.sg link in conjunction with the transition page and b) allow user to also type the link instead of scanning the QR
