### ISSUE TITLE
Add OGP footer

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#587]
**Describe the solution you'd like**
Attribute OGP on all products:
1. Product site/app 
- Include OGP logo
- Include the words (a division of Govtech)
2. Product Pages [DONE]
Include Github handles of all current and past contributors to the project.

**Comment by NatMaeTan** [comment]
Screens are here: https://www.figma.com/file/nnn9vEU4WeMKiddwEUSnAW/Design-Master?node-id=4738%3A403
