### ISSUE TITLE
GoSearch for the whole of government information

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#638]
**Is your feature request related to a problem? Please describe.**
The current GoSearch only fetches go links as results. 
Members of the public are not aware of the existence of shortlinks in general but care more about the content in the destination link. [We also need to log the number of users visiting homepage now to verify this]

The idea is to expand the scope of GoSearch to cover the entire content of the WOG. This makes GoSearch more relevant to the public and helps the public to verify the legitimacy of the content.

Key benefits of Go(v)Search:
1. Legitimacy - public knows that content fetched by GoSearch are legitimate.
2. Convenience - all government information can be found at a single place
3. Marketing/Adoption - it helps agency officers to increase the exposure of their content

Possible key features of Go(v)Search:
1. WOG content search
2. WOG content discovery - could reuse the golinks discovery page designed by the designers

Possible sources of information:
1. Go links
2. Websites
3. Forms
4. Stretch goals - data from data.gov.sg?

ToDos:
1. Crawling of WOG websites - we can start with a few websites from a few agencies (while seeking their permission to do so)
2. Integrating with existing search consoles such as Google Search, Algolia for better search performance
3. Working with a few agencies to pilot the use of such search feature for their content
4. Relating to point 3 - can we use programmatic generation of go shortlinks to help agencies onboard onto gosearch quicker?

Other references:
LMGTFY.com

**Comment by LoneRifle** [comment]
Superseded by similar documents written elsewhere
