### ISSUE TITLE
Runaway API calls to /api/stats in development on fresh install

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/GoGovSG#659]
**Describe the bug**
Runaway API calls to /api/stats in development environment on fresh install

**To Reproduce**
1. Clear all Docker containers, images, volumes
2. Run `npm run dev`
3. Navigate to the home page on http://localhost:3000
4. See runaway network requests

**Expected behavior**
Only one request ought to be made to /api/stats endpoint

**Comment by yong-jie** [comment]
This bug appears to have been present from more than one release back, but was never discovered becasue our machines all had existing data

**Comment by LoneRifle** [comment]
Fixed by #669
