### ISSUE TITLE
Fix QR code generation on Internet Explorer

### ISSUE THREAD

**Issue by waynetee** [opengovsg/GoGovSG#7]
**Describe the bug**
Currently, the QR codes cannot be seen or downloaded on Internet Explorer

**To Reproduce**
1. Log into go.gov.sg
2. Click on QR code icon 

**Expected behavior**
QR code should be visible upon clicking the QR code icon 

**Screenshots**
![image](https://user-images.githubusercontent.com/17681226/78856527-99d87800-7a59-11ea-9808-831e5049f445.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser: IE 11

**Comment by LoneRifle** [comment]
Closed by #22
