### ISSUE TITLE
Bugs on Announcement Modal

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#733]
**Describe the bug**
1. Missing padding in the text body
2. Odd scaling of image in large screens

![Screenshot_20201014-165359](https://user-images.githubusercontent.com/23736580/95967147-80681c80-0e3e-11eb-8e2b-0b213d22b19e.png)
![Screenshot 2020-10-14 at 5 21 30 PM](https://user-images.githubusercontent.com/23736580/95969756-b5c23980-0e41-11eb-9284-e5360115e466.png)
![Screenshot 2020-10-14 at 5 21 21 PM](https://user-images.githubusercontent.com/23736580/95969803-c377bf00-0e41-11eb-8e86-c7a8c87bf1e2.png)

**Comment by LoneRifle** [comment]
The image scaling issues is due to the large block of text competing for screen real estate with the image, with the text taking precedence. I would argue that we should leave the scaling as-is to allow as much text to be displayed within the modal as possible

**Comment by lisatjide** [comment]
fixed and merged
