### ISSUE TITLE
Setup for.edu.sg

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#777]
**Is your feature request related to a problem? Please describe.**
Go.gov.sg is currently only available to gov.sg email users, hence, there is a group of users on edu.sg emails who are not able to access it. They are mainly users from the tertiary institutions such as polytechnics and ITEs. 

**Describe the solution you'd like**
A separate link shortener service for the edu.sg users. This will be hosted on for.edu.sg

**Comment by liangyuanruo** [comment]
@lisatjide can you detail what changes to the application should be made before the infrastructure is set up?
