### ISSUE TITLE
update the states of files created before release of filesharing feature

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#787]
Before the release and addition of isFile column into the database, there were 41 files created for testing purpose and urgent use. 

The state of these files in the isFile column should be updated to True to make sure that our DB is updated with accurate data.

**Comment by lisatjide** [comment]
lisa to send a list of links with incorrect filetype to engineers

**Comment by liangyuanruo** [comment]
@lisatjide do you have the list of files?
