### ISSUE TITLE
granting developers write access to db 

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#800]
details to be figured out

**Comment by liangyuanruo** [comment]
`GRANT EXECUTE ON migrate_user_links,migrate_url_to_user TO rds_readers`

if you want Lisa to have the ability to transfer links

`GRANT EXECUTE ON migrate_user_links,migrate_url_to_user TO rds_iam

 otherwise

**Comment by liangyuanruo** [comment]
Turns out the syntax is `GRANT EXECUTE ON FUNCTION ...`
