### ISSUE TITLE
Use enums for Redux actions

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/GoGovSG#937]
User actions are currently typed as constant value strings. For example, in `src/client/user/actions/types.ts`:

```typescript
/* User actions */
export const CREATE_URL_SUCCESS = 'CREATE_URL_SUCCESS'
export const GET_URLS_FOR_USER_SUCCESS = 'GET_URLS_FOR_USER_SUCCESS'
export const OPEN_CREATE_URL_MODAL = 'OPEN_CREATE_URL_MODAL'
...
```

This causes import bloat in `src/client/user/actions/index.ts`:

```typescript
import {
  // 40 lines of imports
} from './types'
```

Convert the implementation to use TypeScript `enum`s instead.

**Comment by seaerchin** [comment]
Hi, I'm interested in working on this but I'm currently busy with school examinations and won't be able to start till 2nd Dec - would this be fine?

**Comment by liangyuanruo** [comment]
hi @searchin, appreciate your interest in working on this. the development team is striving to clear technical debt this week. we'll see how the progress goes, but you can tackle #938 if this story ends up being taken.
