### ISSUE TITLE
Add Google Analytics to measure transition page drop off

### ISSUE THREAD

**Issue by leonardloo** [opengovsg/GoGovSG#95]
**Is your feature request related to a problem? Please describe.**
We launched transition page, and there have been no agency or citizen complaints, but we are not quantitatively certain transition page is not locking users out of their long links.

**Describe the solution you'd like**
Theoretically can track a) each page's view, and b) emit Proceed button click (by passing in short link too so can map back to page view). If users are not locked out, b) should not be that much lower than a).

This is an important P2. Good to do this sooner rather than later. We just launched transition page and want to make sure users are not locked out.

**Comment by liangyuanruo** [comment]
To clarify - we definitely aren’t locking users out of the target link. The only question is whether they find it a bother to click the Proceed button.

**Comment by leonardloo** [comment]
Judging by no complaints, seems unlikely we are locking users out. But I will not discount this completely for all users.
