### ISSUE TITLE
Use maildev for local development

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/GoGovSG#951]
**Is your feature request related to a problem? Please describe.**
Currently local development requires hardcoding OTPs to "111111" and using the dummy `MailerNoOp` service.

**Describe the solution you'd like**
Integrate [maildev](https://github.com/maildev/maildev) with for use in local development instead. This will close the security risks from accidentally generating dummy OTPs in production, and align development to be closer to the production setup.

**Comment by LoneRifle** [comment]
Instead of that, why not we just stub nodemailer in dev?

**Comment by liangyuanruo** [comment]
I would like to exercise the same nodemailer code path as closely as possible. wit this implementation, the difference will be minimal as only the transport will differ.
