### ISSUE TITLE
Decouple login form input from Redux

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/GoGovSG#955]
**Is your feature request related to a problem? Please describe.**
Each keystroke entering the email and OTP input fields results in an update to the Redux store.

**Describe the solution you'd like**
To decouple each input keystroke so that it no longer updates the Redux store. Instead, updates to Redux should only occur when action buttons such as "sign in" or "submit OTP" are clicked.

**Comment by yong-jie** [comment]
agreed; would also like to add that OTP and email fields aren't needed beyond the component, might also be worth to just store it in state instead of tracking with redux.
