### ISSUE TITLE
Move click count out of URL table

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#984]
**Is your feature request related to a problem? Please describe.**
As we are moving forward with features that require bulk database operations, we want to move click count (a frequently updated field) in the URL table.

This is because updating the click count atomically requires a row lock, and it is unlikely that bulk operations will be able to acquire the necessary locks to proceed if a link is being visited constantly.

**Comment by LoneRifle** [comment]
Sole outstanding issue tracked by #1097
