### ISSUE TITLE
Insert a note on link drawer about sharing through Postman

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/GoGovSG#985]
**Is your feature request related to a problem? Please describe.**
This is an effort to cross sell Postman.gov.sg on Go.gov.sg

**Comment by lisatjide** [comment]
@NatMaeTan do you think you can help with this quickly? just a single liner on `Share your links easily to the public through mass communication tool postman.gov.sg`

**Comment by LoneRifle** [comment]
> @NatMaeTan do you think you can help with this quickly? just a single liner on `Share your links easily to the public through mass communication tool postman.gov.sg`

Copy editing..
`Share your links easily! Reach out to citizens in minutes with Postman.`

**Comment by NatMaeTan** [comment]
Perhaps something like this? Short and simple

![Drawer_Hidden link visibility](https://user-images.githubusercontent.com/63220614/100589372-fa406080-332d-11eb-8998-43780cfb871c.png)

**Comment by lisatjide** [comment]
@NatMaeTan looks good!
